### ISSUE TITLE
Defining a message handler in a module

### ISSUE THREAD

**Issue by adamcohen** [slackapi/node-slack-interactive-messages#48]
### Description

I've followed the [Express All Interactions Example](https://github.com/slackapi/node-slack-interactive-messages/tree/master/examples/express-all-interactions) and it defines all interactive message handlers inside `server.js`, which is fine for a small project, but I'm trying to understand how best to define message handlers for use in a large project composed of many different modules.

For example, say I have a `project` module, and I want this to contain the logic for an `updateProject` action.  I've been able to do this using the following structure:

```
// server.js
const project = require('./path/to/project')
const slackInteractions = createMessageAdapter(process.env.SLACK_VERIFICATION_TOKEN);
app.use('/slack/actions', slackInteractions.expressMiddleware());
project.initInteractionHandlers(slackInteractions)

// project.js
module.exports.initInteractionHandlers = function(slackInteractions) {
  slackInteractions.action('updateProject', (payload, respond) => {
    console.log(`The user ${payload.user.name} in team ${payload.team.domain} submitted a dialog`);
  }
}
```

The above example works, but I'm not sure if this is the correct way to handle this.  Can someone please let me know if I'm on the right track, or if there's a better way to handle it?

Ideally, it would be great to have another example added to the [Express All Interactions Example](https://github.com/slackapi/node-slack-interactive-messages/tree/master/examples/express-all-interactions) to show exactly how to define a handler outside of `server.js`.  Thanks!

### What type of issue is this?
- [x] question

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-interactive-messages/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
@adamcohen you raised an interesting point: we haven't provided any guidance on how to modularize an application using this adapter. in `express` parlance, the question is "what's the equivalent of an `express.Router` for the adapter?"

if this worked like `express`, you'd instantiate a mini-adapter inside one module, and then export it. then some other module would aggregate all the mini-adapters and mount them into the larger adapter. but at this point i'm not certain it should be the job of this package to provide a mini-adapter.

i see this package as a low-level component that should remain as flexible as possible, so that any application developer or framework can use it and adapt it to whichever pattern they prefer.

but as you are pointing out, its unhelpful to leave app developers off to figure out a reasonable pattern all on their own. so in short, i agree with you that a new example app may be the best vehicle to demonstrate this usage and provide reasonable guidelines.

---

getting to the actual implementation. i think its reasonable for your `project.js` to import `@slack/interactive-messages`, and call `createMessageAdapter()` directly. then it would export the return value of `slackInteractions.expressMiddleware(), which `server.js` would import. this would allow `server.js` to remain decoupled from the idea of how slack messages are handled and what the adapter does, it only deals in HTTP middleware. then `server.js`'s job becomes to mount that middleware on the desired path and run the server. one day, if your project gains another module like `project.js`, that module can also create its own message adapter, completely independent of the first, and export its middleware.

does this sound like a reasonable approach for the application you are building? once we come up with something that works for you, i'm happy to turn that into a spec for a sample, and work on landing that (maybe even from you)!

---

thanks for kicking off this discussion.

**Comment by adamcohen** [comment]
I've been playing around a bit more and have run into a bit of blocker.  I'm trying to use a `project` module and define the interactive message hander in a class:

**slack-interactions.js**
```javascript
const { createMessageAdapter } = require('@slack/interactive-messages');
module.exports = createMessageAdapter(process.env.SLACK_VERIFICATION_TOKEN);
```

**server.js**
```javascript
const project = require('./project');
app.use('/slack/actions', project.interactionDispatcherMiddleware);
```

**project.js**
```javascript
const slackInteractions = require('./slack-interactions')

class Project {
  constructor() {
    slackInteractions.action('project.select', this.projectSelect)
    this.interactionDispatcherMiddleware = slackInteractions.expressMiddleware()
  }

  async projectSelect(payload, respond) {
    try {
      const selectedID = payload.actions[0].selected_options[0].value 
      const project = await Project.findByID(selectedID)

      const someResult = await this.doSomething()
      respond({ text: `Project name ${project.name} was selected. Result: ${someResult}` });
    } catch (err) {
      respond({ text: `An error occurred: ${err}` });
    }
  }

  async doSomething() {
    // implement me
  }
}
```

The above fails with `project.select TypeError: this.doSomething is not a function` because the middleware function doesn't have access to instance methods in the class.  I can't seem to figure out how to get around this, since it seems like I would need to pass an instance of the class when calling `slackInteractions.expressMiddleware()`. If you have any ideas how to solve this, I'd appreciate it.

**Comment by adamcohen** [comment]
@aoberoi any thoughts about how to get `node-slack-interactive-messages` to allow access to class level functions from within the middleware callback?  I've found [the following](https://stackoverflow.com/questions/39932009/node-express-middleware) stackoverflow question which seems similar to what I'm trying to do, and one of the answers is to use:

```
app.use(Middle.middleware(middle));
```

Which looks like it would require a change on your end to allow me to call `slackInteractions.expressMiddleware()` and provide an argument.  Is that correct, or is it possible to solve this without any changes in the `node-slack-interactive-messages` package?

**Comment by shanedewael** [comment]
Hi @adamcohen,

I'm going to close this issue out since been a while since the last reply. It seems like you may have figured this one out. If not, feel free to open a new issue in https://github.com/slackapi/node-slack-sdk/issues which is the new home for this project.
